version = 0.1

[default.deploy.parameters]
stack_name = "agro-bot"
resolve_s3 = true
s3_prefix = "agro-bot"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
